### ISSUE TITLE
Data generation: traced quantities

### ISSUE THREAD

**Issue by MilanStaffehl** [MilanStaffehl/TNG-Cluster-paper#189]
Save to archive the following quantities of every traced gas particle (on a per-tracer-per-snapshot basis!):

- [x] Mass in $M_\odot$
- [x] Temperature in K
- [x] Density
- [x] Host halo ID - see #195 
- [x] Host subhalo ID - see #195 
- [x] Distance to main progenitor in ckpc
- [ ] Distance to parent group in ckpc (set to NaN for unbound particles)
- [ ] Distance to parent subhalo in ckpc (set to NaN for unbound particles)
- [ ] Radial velocity w.r.t. main progenitor
- [ ] Radial velocity w.r.t. parent group (set to NaN for unbound particles)
- [ ] Radial velocity w.r.t. subhalo in (set to NaN for unbound particles)

As postprocessing:

- [x] Membership flag: category of particle - see #190 
- [x] Time of first and last crossing - see #185 

This is a tracking issue to run in parallel with the following issues:

- #179 
- #180 
- #181 
- #183
